server:
  port: 8888

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/testAPI
    username: your_username
    password: your_password
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true